//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Id { get; set; }
        public string DeparturePoint { get; set; }
        public string ArrivalPoint { get; set; }
        public string TimeDeparture { get; set; }
        public string TimeArrival { get; set; }
        public Nullable<int> TransportId { get; set; }
    
        public virtual Transport Transport { get; set; }
    }
}
